[package]
name = "serde-toml-issue"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]

[dependencies]
toml = { version = "0.2", features = ["serde"], default-features = false }
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
